// Fictional demonstration inventory. Brand labels are filter data, not real listings.
// All garment specifications belong to this fictional simulation, with no brand logos.
// Positive stock means repeat purchases have no quantity cap; unavailable variants
// are deterministic. Prices are integer cents, never floating point dollars.
// Eleven entries are advertisements only; they retain metadata for filtering.
export const PRODUCTS = [
  {"id": "tee", "name": "Everyday cotton tee", "brand": "Nike", "type": "Tops", "priceCents": 1800, "colors": ["White", "Blue"], "sizes": ["S", "M", "L"], "unavailable": ["Blue|S"], "image": "tee.webp", "shape": "short", "description": "An easy, relaxed silhouette in substantial cotton. A simple starting point for the everyday wardrobe.", "categories": ["tops", "t-shirts"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS"], "occasions": [], "colorSchemes": []},
  {"id": "jeans", "name": "Straight-leg denim", "brand": "Puma", "type": "Pants", "priceCents": 3200, "colors": ["Blue", "Black"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "jeans.webp", "shape": "tall", "description": "A straight cut with a lived-in blue wash. Mid-rise, full-length denim with room to move.", "categories": ["pants", "bottoms", "jeans", "trousers"], "materials": ["denim", "cotton"], "fits": ["straight-fit"], "audiences": ["unisex"], "seasons": ["SS", "FW"], "occasions": [], "colorSchemes": []},
  {"id": "green-jacket", "name": "Lightweight field jacket", "brand": "Nike", "type": "Outer", "priceCents": 4500, "colors": ["Green", "Black"], "sizes": ["S", "M", "L"], "unavailable": ["Green|M"], "image": "green-jacket.webp", "shape": "medium", "description": "A light layer with a clean zip front. Made for the space between one season and the next.", "categories": ["outer", "field-jackets", "long-sleeves", "jip-up"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS", "FW"], "occasions": [], "colorSchemes": []},
  {"id": "sweatshirt", "name": "Loopback sweatshirt", "brand": "Puma", "type": "Tops", "priceCents": 2700, "colors": ["Charcoal", "Blue"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "sweatshirt.webp", "shape": "short", "description": "Soft loopback texture, dropped shoulders and a familiar crew neckline. An everyday essential.", "categories": ["tops", "sweatwear", "long-sleeves"], "materials": ["cotton"], "fits": ["over-fit", "loose-fit"], "audiences": ["unisex"], "seasons": ["FW"], "occasions": [], "colorSchemes": []},
  {"id": "trousers", "name": "Pleated city trousers", "brand": "Nike", "type": "Pants", "priceCents": 3900, "colors": ["Blue", "Black"], "sizes": ["S", "M", "L"], "unavailable": ["Black|S"], "image": "trousers.webp", "shape": "tall", "description": "A relaxed drape with a single front pleat. A considered shape that works throughout the week.", "categories": ["pants", "bottoms", "trousers"], "materials": [], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS", "FW"], "occasions": ["office-wear"], "colorSchemes": []},
  {"id": "bomber", "name": "Volume bomber jacket", "brand": "Puma", "type": "Outer", "priceCents": 6400, "colors": ["Black", "Green"], "sizes": ["S", "M", "L"], "unavailable": ["Black|L"], "image": "bomber.webp", "shape": "medium", "description": "A rounded silhouette with ribbed edges and a clean zip front. Cut to layer over your daily staples.", "categories": ["outer", "ma-1", "blousons", "jip-up", "long-sleeves"], "materials": [], "fits": ["oversize", "over-fit"], "audiences": ["unisex"], "seasons": ["FW"], "occasions": [], "colorSchemes": []},
  {"id": "trench", "name": "Longline trench coat", "brand": "Nike", "type": "Outer", "priceCents": 11800, "colors": ["Taupe", "Blue"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "trench.webp", "shape": "tall", "description": "An understated longline coat with a soft belt and structured collar. A familiar form, reworked.", "categories": ["outer", "long-sleeves"], "materials": [], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS", "FW"], "occasions": ["office-wear"], "colorSchemes": []},
  {"id": "polo", "name": "Textured cotton polo", "brand": "Puma", "type": "Tops", "priceCents": 2300, "colors": ["Green", "White"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "polo.webp", "shape": "short", "description": "A textured knit with an open collar and relaxed sleeves. For a slightly different kind of everyday.", "categories": ["tops", "shirts"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS"], "occasions": [], "colorSchemes": []},
  {"id": "knit", "name": "Cable-knit crewneck", "brand": "Nike", "type": "Tops", "priceCents": 5100, "colors": ["Cream", "Green"], "sizes": ["S", "M", "L"], "unavailable": ["Cream|S"], "image": "knit.webp", "shape": "medium", "description": "Dimensional cables in a soft, substantial knit. Easy volume with a gently ribbed hem.", "categories": ["tops", "long-sleeves"], "materials": [], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["FW"], "occasions": [], "colorSchemes": []},
  {"id": "shirt", "name": "Oxford weekend shirt", "brand": "Puma", "type": "Tops", "priceCents": 3600, "colors": ["Blue", "White"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "shirt.webp", "shape": "medium", "description": "A crisp Oxford weave with an easy fit. Button it up or wear it open over a cotton tee.", "categories": ["tops", "shirts", "long-sleeves"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS", "FW"], "occasions": ["office-wear"], "colorSchemes": []},
  {"id": "jeans-indigo", "name": "Indigo wide-leg jeans", "brand": "Dickies", "type": "Pants", "priceCents": 4400, "colors": ["Blue"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "jeans-indigo.webp", "shape": "tall", "description": "Deep indigo denim in a wide-leg silhouette. Classic five-pocket construction with a clean, full-length finish.", "categories": ["pants", "bottoms", "trousers", "jeans"], "materials": ["denim", "cotton"], "fits": ["wide-fit"], "audiences": ["unisex"], "seasons": ["SS", "FW"], "occasions": [], "colorSchemes": [], "addedIn": "v2", "garmentKind": "jeans"},
  {"id": "jeans-washed", "name": "Washed straight-leg jeans", "brand": "Stussy", "type": "Pants", "priceCents": 3800, "colors": ["Blue"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "jeans-washed.webp", "shape": "tall", "description": "Pale washed denim with a straight leg and familiar five-pocket construction. An easy everyday shape.", "categories": ["pants", "bottoms", "trousers", "jeans"], "materials": ["denim", "cotton"], "fits": ["straight-fit"], "audiences": ["unisex"], "seasons": ["SS", "FW"], "occasions": [], "colorSchemes": [], "addedIn": "v2", "garmentKind": "jeans"},
  {"id": "chino-olive", "name": "Olive slim chino trousers", "brand": "Brownyard", "type": "Pants", "priceCents": 4200, "colors": ["Olive"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "chino-olive.webp", "shape": "tall", "description": "Olive cotton chinos with a slim leg and an understated finish. A neat shape for everyday dressing.", "categories": ["pants", "bottoms", "trousers", "chino"], "materials": ["cotton"], "fits": ["slim-fit"], "audiences": ["unisex"], "seasons": ["SS", "FW"], "occasions": ["office-wear"], "colorSchemes": [], "addedIn": "v2", "garmentKind": "chino"},
  {"id": "chino-sand", "name": "Sand straight chino trousers", "brand": "Nanamica", "type": "Pants", "priceCents": 4600, "colors": ["Sand"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "chino-sand.webp", "shape": "tall", "description": "Sand cotton chinos with a straight leg and clean waistband. Soft structure for the working week.", "categories": ["pants", "bottoms", "trousers", "chino"], "materials": ["cotton"], "fits": ["straight-fit"], "audiences": ["unisex"], "seasons": ["SS", "FW"], "occasions": ["office-wear"], "colorSchemes": [], "addedIn": "v2", "garmentKind": "chino", "isAd": true},
  {"id": "sweatpants-gray", "name": "Heather loopback sweatpants", "brand": "Adidas", "type": "Pants", "priceCents": 3400, "colors": ["Gray"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "sweatpants-gray.webp", "shape": "tall", "description": "Heather gray cotton fleece with a relaxed leg, elastic waistband and simple drawstring. Easy to wear all day.", "categories": ["pants", "bottoms", "trousers", "sweatwear", "fleece"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS", "FW"], "occasions": [], "colorSchemes": [], "addedIn": "v2", "garmentKind": "sweatpants", "isAd": true},
  {"id": "graphic-tee-black", "name": "Orbit graphic tee", "brand": "Supreme", "type": "Tops", "priceCents": 2200, "colors": ["Black"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "graphic-tee-black.webp", "shape": "short", "description": "A black cotton crewneck with an original cream orbital graphic. Short sleeves and an easy, relaxed fit.", "categories": ["tops", "t-shirts"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS"], "occasions": [], "colorSchemes": [], "addedIn": "v2", "garmentKind": "graphic-tee"},
  {"id": "graphic-tee-burgundy", "name": "Geometry graphic tee", "brand": "BAPE", "type": "Tops", "priceCents": 2500, "colors": ["Burgundy"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "graphic-tee-burgundy.webp", "shape": "short", "description": "A burgundy cotton crewneck with an original ivory geometric print. A simple shape with a graphic point of view.", "categories": ["tops", "t-shirts"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS"], "occasions": [], "colorSchemes": [], "addedIn": "v2", "garmentKind": "graphic-tee", "isAd": true},
  {"id": "graphic-tee-navy", "name": "Sunrise graphic tee", "brand": "Human-Made", "type": "Tops", "priceCents": 2800, "colors": ["Navy"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "graphic-tee-navy.webp", "shape": "short", "description": "An orange sun graphic sits on a navy cotton crewneck. Short sleeves and a relaxed everyday silhouette.", "categories": ["tops", "t-shirts"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS"], "occasions": [], "colorSchemes": [], "addedIn": "v2", "garmentKind": "graphic-tee", "isAd": true},
  {"id": "graphic-tee-green", "name": "Botanical graphic tee", "brand": "Polyteru", "type": "Tops", "priceCents": 2600, "colors": ["Green"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "graphic-tee-green.webp", "shape": "short", "description": "Forest green cotton with a pale botanical silhouette across the chest. Cut with short sleeves and room to move.", "categories": ["tops", "t-shirts"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS"], "occasions": [], "colorSchemes": [], "addedIn": "v2", "garmentKind": "graphic-tee"},
  {"id": "graphic-tee-cream", "name": "Wave graphic tee", "brand": "TINT", "type": "Tops", "priceCents": 2400, "colors": ["Cream"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "graphic-tee-cream.webp", "shape": "short", "description": "A cream cotton crewneck with an original cobalt wave print. A fluid graphic on a familiar everyday shape.", "categories": ["tops", "t-shirts"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS"], "occasions": [], "colorSchemes": [], "addedIn": "v2", "garmentKind": "graphic-tee", "isAd": true},
  {"id": "plain-tee-white", "name": "Essential white tee", "brand": "Union-Blue", "type": "Tops", "priceCents": 1600, "colors": ["White"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "plain-tee-white.webp", "shape": "short", "description": "A plain white cotton crewneck with short sleeves. A clean, relaxed staple with no graphic or lettering.", "categories": ["tops", "t-shirts"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS"], "occasions": [], "colorSchemes": [], "addedIn": "v2", "garmentKind": "plain-tee", "isAd": true},
  {"id": "plain-tee-gray", "name": "Essential gray tee", "brand": "ON", "type": "Tops", "priceCents": 1900, "colors": ["Gray"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "plain-tee-gray.webp", "shape": "short", "description": "A plain gray cotton crewneck with short sleeves. Soft texture and a simple relaxed silhouette.", "categories": ["tops", "t-shirts"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS"], "occasions": [], "colorSchemes": [], "addedIn": "v2", "garmentKind": "plain-tee"},
  {"id": "plain-tee-olive", "name": "Essential olive tee", "brand": "Hatchingroom", "type": "Tops", "priceCents": 1700, "colors": ["Olive"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "plain-tee-olive.webp", "shape": "short", "description": "A plain olive cotton crewneck with short sleeves. A quiet color and a comfortable everyday fit.", "categories": ["tops", "t-shirts"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS"], "occasions": [], "colorSchemes": [], "addedIn": "v2", "garmentKind": "plain-tee", "isAd": true},
  {"id": "plain-tee-brown", "name": "Essential brown tee", "brand": "Gonak", "type": "Tops", "priceCents": 2000, "colors": ["Brown"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "plain-tee-brown.webp", "shape": "short", "description": "A plain brown cotton crewneck with short sleeves. An earthy shade in an easy, relaxed shape.", "categories": ["tops", "t-shirts"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS"], "occasions": [], "colorSchemes": [], "addedIn": "v2", "garmentKind": "plain-tee", "isAd": true},
  {"id": "plain-tee-blue", "name": "Essential sky-blue tee", "brand": "Kinch!", "type": "Tops", "priceCents": 2100, "colors": ["Blue"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "plain-tee-blue.webp", "shape": "short", "description": "A plain sky-blue cotton crewneck with short sleeves. Soft color and a clean everyday silhouette.", "categories": ["tops", "t-shirts"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS"], "occasions": [], "colorSchemes": [], "addedIn": "v2", "garmentKind": "plain-tee"},
  {"id": "striped-long-tee", "name": "Mariner striped long-sleeve tee", "brand": "Comme-des Garcon", "type": "Tops", "priceCents": 3100, "colors": ["Cream"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "striped-long-tee.webp", "shape": "medium", "description": "Cream and navy horizontal stripes run across a cotton crewneck with long sleeves. A familiar mariner-inspired design.", "categories": ["tops", "t-shirts", "long-sleeves"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["FW"], "occasions": [], "colorSchemes": [], "addedIn": "v2", "garmentKind": "long-tee"},
  {"id": "raglan-long-tee", "name": "Contrast raglan long-sleeve tee", "brand": "Needles", "type": "Tops", "priceCents": 3300, "colors": ["White"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "raglan-long-tee.webp", "shape": "medium", "description": "A white cotton body with contrasting burgundy raglan sleeves. An easy long-sleeve shape with a sporting influence.", "categories": ["tops", "t-shirts", "long-sleeves"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["FW"], "occasions": [], "colorSchemes": [], "addedIn": "v2", "garmentKind": "long-tee"},
  {"id": "pocket-long-tee", "name": "Contrast pocket long-sleeve tee", "brand": "ADDERERROR", "type": "Tops", "priceCents": 2900, "colors": ["Black"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "pocket-long-tee.webp", "shape": "medium", "description": "A black cotton long-sleeve tee with a gray patch pocket. A subtle contrast on a clean crewneck silhouette.", "categories": ["tops", "t-shirts", "long-sleeves"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["FW"], "occasions": [], "colorSchemes": [], "addedIn": "v2", "garmentKind": "long-tee"},
  {"id": "oxford-shirt-white", "name": "Crisp long-sleeve Oxford shirt", "brand": "Another-Office", "type": "Tops", "priceCents": 4100, "colors": ["White"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "oxford-shirt-white.webp", "shape": "medium", "description": "A white cotton Oxford shirt with a classic collar and long sleeves. Crisp texture with an easy, straight silhouette.", "categories": ["tops", "shirts", "long-sleeves"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS", "FW"], "occasions": ["office-wear"], "colorSchemes": [], "addedIn": "v2", "garmentKind": "long-shirt", "isAd": true},
  {"id": "linen-shirt-navy", "name": "Navy linen long-sleeve shirt", "brand": "Lemaire", "type": "Tops", "priceCents": 4800, "colors": ["Navy"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "linen-shirt-navy.webp", "shape": "medium", "description": "Navy linen with a soft drape, button front and long sleeves. Light texture for an unhurried everyday look.", "categories": ["tops", "shirts", "long-sleeves"], "materials": ["linen"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS"], "occasions": ["office-wear"], "colorSchemes": [], "addedIn": "v2", "garmentKind": "long-shirt"},
  {"id": "check-shirt-olive", "name": "Olive check long-sleeve shirt", "brand": "Comori", "type": "Tops", "priceCents": 4300, "colors": ["Olive"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "check-shirt-olive.webp", "shape": "medium", "description": "Olive and cream checks on a cotton button-front shirt. Long sleeves and a relaxed shape make it an easy layer.", "categories": ["tops", "shirts", "long-sleeves"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS", "FW"], "occasions": [], "colorSchemes": [], "addedIn": "v2", "garmentKind": "long-shirt", "isAd": true},
  {"id": "camp-shirt-cream", "name": "Cream camp-collar shirt", "brand": "Aurari", "type": "Tops", "priceCents": 3700, "colors": ["Cream"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "camp-shirt-cream.webp", "shape": "short", "description": "A cream short-sleeve shirt with an open camp collar. An airy silhouette with a relaxed button-front finish.", "categories": ["tops", "shirts"], "materials": ["linen"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS"], "occasions": ["beachwear"], "colorSchemes": [], "addedIn": "v2", "garmentKind": "short-shirt"},
  {"id": "stripe-shirt-blue", "name": "Blue stripe short-sleeve shirt", "brand": "Masion-Kitsune", "type": "Tops", "priceCents": 3900, "colors": ["Blue"], "sizes": ["S", "M", "L"], "unavailable": [], "image": "stripe-shirt-blue.webp", "shape": "short", "description": "Fine white stripes on a light blue short-sleeve shirt. A clean collar and soft cotton keep the shape easy.", "categories": ["tops", "shirts"], "materials": ["cotton"], "fits": ["loose-fit"], "audiences": ["unisex"], "seasons": ["SS"], "occasions": ["office-wear"], "colorSchemes": [], "addedIn": "v2", "garmentKind": "short-shirt", "isAd": true},
];

// Ads lead the fixed catalog order; masonry distributes them across the top.
export const CATALOG_ORDER = ["graphic-tee-burgundy", "sweatpants-gray", "check-shirt-olive", "graphic-tee-navy", "plain-tee-brown", "plain-tee-olive", "plain-tee-white", "oxford-shirt-white", "chino-sand", "stripe-shirt-blue", "graphic-tee-cream", "jeans", "shirt", "tee", "trousers", "sweatshirt", "jeans-indigo", "green-jacket", "jeans-washed", "pocket-long-tee", "raglan-long-tee", "bomber", "graphic-tee-black", "linen-shirt-navy", "striped-long-tee", "graphic-tee-green", "chino-olive", "camp-shirt-cream", "trench", "plain-tee-blue", "plain-tee-gray", "knit", "polo"];
export const ADS = [
  {"id": "ad-graphic-tee-burgundy", "sourceProductId": "graphic-tee-burgundy", "title": "A different everyday.", "body": "This is a simulated fashion advertisement. This image is not a purchasable item. Close this window to continue exploring the collection."},
  {"id": "ad-sweatpants-gray", "sourceProductId": "sweatpants-gray", "title": "Room to unwind.", "body": "This is a simulated fashion advertisement. This image is not a purchasable item. Close this window to continue exploring the collection."},
  {"id": "ad-check-shirt-olive", "sourceProductId": "check-shirt-olive", "title": "Between the lines.", "body": "This is a simulated fashion advertisement. This image is not a purchasable item. Close this window to continue exploring the collection."},
  {"id": "ad-graphic-tee-navy", "sourceProductId": "graphic-tee-navy", "title": "A brighter point of view.", "body": "This is a simulated fashion advertisement. This image is not a purchasable item. Close this window to continue exploring the collection."},
  {"id": "ad-plain-tee-brown", "sourceProductId": "plain-tee-brown", "title": "Grounded in color.", "body": "This is a simulated fashion advertisement. This image is not a purchasable item. Close this window to continue exploring the collection."},
  {"id": "ad-plain-tee-olive", "sourceProductId": "plain-tee-olive", "title": "A quieter statement.", "body": "This is a simulated fashion advertisement. This image is not a purchasable item. Close this window to continue exploring the collection."},
  {"id": "ad-plain-tee-white", "sourceProductId": "plain-tee-white", "title": "Start with a blank canvas.", "body": "This is a simulated fashion advertisement. This image is not a purchasable item. Close this window to continue exploring the collection."},
  {"id": "ad-oxford-shirt-white", "sourceProductId": "oxford-shirt-white", "title": "Consider the familiar.", "body": "This is a simulated fashion advertisement. This image is not a purchasable item. Close this window to continue exploring the collection."},
  {"id": "ad-chino-sand", "sourceProductId": "chino-sand", "title": "An easy kind of structure.", "body": "This is a simulated fashion advertisement. This image is not a purchasable item. Close this window to continue exploring the collection."},
  {"id": "ad-stripe-shirt-blue", "sourceProductId": "stripe-shirt-blue", "title": "Find your own rhythm.", "body": "This is a simulated fashion advertisement. This image is not a purchasable item. Close this window to continue exploring the collection."},
  {"id": "ad-graphic-tee-cream", "sourceProductId": "graphic-tee-cream", "title": "Go with the flow.", "body": "This is a simulated fashion advertisement. This image is not a purchasable item. Close this window to continue exploring the collection."},
];
